on:
  release:
    types: [published]
jobs:
  release_windows:
    runs-on: unbuntu-latest
    steps:
      - name: download Windows
        id: download-windows
        uses: dsaltares/fetch-gh-release-asset@main
        with:
          file: guessthenumber-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CREDENTIALS }}
      - name: deploy to itch.io (Windows)
        uses: josephbman/butler-publish-itchio-action@main
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: guessthenumber
          ITCH_USER: bobbygrdn
          PACKAGE: guessthenumber-windows.zip
          VERSION: ${{ steps.download-windows.outputs.version }}
